import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "СТОГИД - Категории",
  // description: "Generated by create next app",
};

export default function Category() {
    return (
      <main className="flexh-full flex-col items-center justify-between bg-white text-black">
          <div className="container max-w-screen-lg mx-auto">
            <div className="directory-item w-full px-4 flex flex-col gap-4 justify-center">
              <h1 className="text-2xl font-semibold text-center">Категории</h1>
            </div>
          </div>
      </main>
    );
  }
  