import StoGidButton from "@/components/forms/button";
import StoGidInput from "@/components/forms/input";
import StoGidTextarea from "@/components/forms/textarea";
import StoGidUserAdreement from "@/components/forms/userAgreement";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "СТОГИД - Контакты",
  // description: "Generated by create next app",
};

export default function Contacts() {
    return (
      <main className="flexh-full flex-col items-center justify-between bg-white text-black">
          <div className="container max-w-screen-lg mx-auto">
            <div className="h-min100-page w-full px-4 py-10 flex flex-col gap-4 gap-y-6">
              <h1 className="text-2xl font-semibold text-center">Контакты</h1>
              <form className="flex flex-col gap-2 gap-y-4 items-center">
                <StoGidInput id="contactEmail" type="email" name="contactEmail" label="Электронная почта" placeholder="email@company.ru" svg="email" />
                <StoGidTextarea id="contactDescription" name="contactDescription" label="Сообщение" placeholder="Оставьте здесь Ваше сообщение" />
                <StoGidButton text="Отправить" />
                <StoGidUserAdreement buttonText="Отправить" />
              </form>
            </div>
          </div>
      </main>
    );
  }
  